### ISSUE TITLE
Ahri name

### ISSUE THREAD

**Issue by itzvenom** [tufanYavas/LoL-TFT-Champion-Masking#1]
Doesn't seem to detect well Ahri's name even though her name is spelled right on the worker.py file.

**Comment by tufanYavas** [comment]
Fixed in new version. 
If origional champion name Ahri and tesseract read as Abri, you should add a line similar function (from worker.py) 
`if a=="Ahri" and b=="Abri":
        return 1`
lines. Because of similar("Ahri","Abri") = 0.75 and we need similar rate > .801 (worker.py line 139)
